import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';

const $=id=>document.getElementById(id);
const DB_NAME='paper-reader-db', STORE='pdfs';
let db=null, pdfDoc=null, currentBook=null, currentPage=1, scale=1.25, renderTask=null, searchToken=0, renderToken=0, searchMatches=[], searchQuery='', searchIndex=-1, annotationColor='yellow', localAiEngine=null, localAiLoading=null, aiSelection='';

function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),1600)}
function showLoader(show,title='Abriendo PDF…',text='Preparando documento'){ $('loader').classList.toggle('show',show);$('loaderTitle').textContent=title;$('loaderText').textContent=text }
function key(id,suffix){return `paper.${id}.${suffix}`}
function getJSON(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function setJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
function bookId(file){return `${file.name}:${file.size}:${file.lastModified}`}

function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function dbPut(record){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function dbGet(id){return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function dbAll(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function dbDelete(id){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}

async function renderLibrary(){const books=(await dbAll()).sort((a,b)=>b.openedAt-a.openedAt);$('library').innerHTML=books.length?books.map(b=>`<button class="book ${currentBook?.id===b.id?'active':''}" data-id="${encodeURIComponent(b.id)}"><strong>${escapeHtml(b.name)}</strong><small>${b.pages?b.pages+' páginas · ':''}${new Date(b.openedAt).toLocaleDateString()}</small></button>`).join(''):'<span style="color:var(--muted);font-size:13px">Aún no hay PDFs guardados.</span>';document.querySelectorAll('.book').forEach(el=>{el.onclick=()=>openStored(decodeURIComponent(el.dataset.id));el.oncontextmenu=async e=>{e.preventDefault();if(confirm('¿Eliminar este PDF de la biblioteca local?')){await dbDelete(decodeURIComponent(el.dataset.id));if(currentBook?.id===decodeURIComponent(el.dataset.id)){pdfDoc=null;currentBook=null;showEmpty()}await renderLibrary()}}})}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}

async function addFile(file){if(!file)return;if(!(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')))return toast('Selecciona un PDF');showLoader(true,'Guardando PDF…','Se queda solo en este dispositivo');try{const id=bookId(file),buffer=await file.arrayBuffer();await dbPut({id,name:file.name,blob:new Blob([buffer],{type:'application/pdf'}),openedAt:Date.now(),pages:null});await openStored(id)}catch(e){console.error(e);toast('No se pudo guardar el PDF')}finally{showLoader(false)}}
async function openStored(id){showLoader(true);try{const rec=await dbGet(id);if(!rec)throw new Error('Documento no encontrado');const bytes=new Uint8Array(await rec.blob.arrayBuffer());pdfDoc=await pdfjsLib.getDocument({data:bytes}).promise;rec.pages=pdfDoc.numPages;rec.openedAt=Date.now();await dbPut(rec);currentBook=rec;currentPage=Math.min(Number(localStorage.getItem(key(id,'page'))||1),pdfDoc.numPages);scale=Number(localStorage.getItem(key(id,'scale'))||1.25);$('emptyState').hidden=true;$('canvasWrap').hidden=false;$('docTitle').textContent=rec.name;$('docMeta').textContent=`${pdfDoc.numPages} páginas · guardado localmente`;await renderPage(currentPage);renderBookmarks();await renderOutline();renderLibrary();document.body.classList.remove('sidebar-open')}catch(e){console.error(e);toast('No se pudo abrir el PDF')}finally{showLoader(false)}}

async function renderPage(num){if(!pdfDoc)return;const token=++renderToken;if(renderTask){try{renderTask.cancel()}catch{}}hideAnnotationActions();currentPage=Math.max(1,Math.min(pdfDoc.numPages,num));const page=await pdfDoc.getPage(currentPage);if(token!==renderToken)return;const viewport=page.getViewport({scale});const dpr=Math.min(window.devicePixelRatio||1,2);const canvas=$('pdfCanvas'),ctx=canvas.getContext('2d');canvas.width=Math.floor(viewport.width*dpr);canvas.height=Math.floor(viewport.height*dpr);canvas.style.width=`${viewport.width}px`;canvas.style.height=`${viewport.height}px`;$('canvasWrap').style.width=`${viewport.width}px`;$('canvasWrap').style.height=`${viewport.height}px`;renderTask=page.render({canvasContext:ctx,viewport,transform:[dpr,0,0,dpr,0,0]});await renderTask.promise.catch(()=>{});if(token!==renderToken)return;localStorage.setItem(key(currentBook.id,'page'),String(currentPage));localStorage.setItem(key(currentBook.id,'scale'),String(scale));$('pageStatus').textContent=`Página ${currentPage} de ${pdfDoc.numPages}`;$('pageJump').value=currentPage;$('pageJump').max=pdfDoc.numPages;$('pageJump').hidden=false;$('progressBar').style.width=`${(currentPage/pdfDoc.numPages)*100}%`;$('prevBtn').disabled=currentPage===1;$('nextBtn').disabled=currentPage===pdfDoc.numPages;$('viewer').scrollTo({top:0,left:0});await renderTextLayer(page,viewport);if(token!==renderToken)return;renderAnnotations()}
async function renderTextLayer(page,viewport){const layer=$('textLayer');layer.innerHTML='';layer.style.width=`${viewport.width}px`;layer.style.height=`${viewport.height}px`;try{const tc=await page.getTextContent();for(const item of tc.items){if(!item.str)continue;const tx=pdfjsLib.Util.transform(viewport.transform,item.transform);const span=document.createElement('span');span.textContent=item.str;span.style.left=`${tx[4]}px`;span.style.top=`${tx[5]}px`;span.style.fontSize=`${Math.hypot(tx[2],tx[3])}px`;layer.appendChild(span)}}catch{}}

async function fitWidth(){if(!pdfDoc)return;const p=await pdfDoc.getPage(currentPage);const base=p.getViewport({scale:1});const available=$('viewer').clientWidth-24;scale=Math.max(.35,Math.min(3,available/base.width));renderPage(currentPage)}
function zoom(delta){scale=Math.max(.4,Math.min(3.5,scale+delta));renderPage(currentPage)}
function renderBookmarks(){if(!currentBook){$('bookmarkList').innerHTML='';return}const list=getJSON(key(currentBook.id,'bookmarks'),[]);$('bookmarkList').innerHTML=list.length?list.sort((a,b)=>a-b).map(p=>`<button class="bookmark" data-p="${p}"><strong>Página ${p}</strong><small>Ir al marcador</small></button>`).join(''):'<span style="color:var(--muted);font-size:13px">Sin marcadores.</span>';document.querySelectorAll('.bookmark').forEach(b=>b.onclick=()=>renderPage(Number(b.dataset.p)))}
function toggleBookmark(){if(!currentBook)return;let list=getJSON(key(currentBook.id,'bookmarks'),[]);if(list.includes(currentPage)){list=list.filter(p=>p!==currentPage);toast('Marcador eliminado')}else{list.push(currentPage);toast('Página marcada')}setJSON(key(currentBook.id,'bookmarks'),list);renderBookmarks()}
async function renderOutline(){const root=$('outlineList');root.innerHTML='';if(!pdfDoc)return;try{const outline=await pdfDoc.getOutline();if(!outline?.length){root.innerHTML='<span style="color:var(--muted);font-size:13px">Este PDF no incluye índice.</span>';return}const addItems=async(items,depth=0)=>{for(const item of items){const button=document.createElement('button');button.className='outline-item';button.textContent=item.title||'Sin título';button.style.paddingLeft=`${9+depth*12}px`;button.onclick=async()=>{try{let dest=item.dest;if(typeof dest==='string')dest=await pdfDoc.getDestination(dest);if(!Array.isArray(dest)||!dest[0])throw new Error();await renderPage((await pdfDoc.getPageIndex(dest[0]))+1)}catch{toast('No se pudo abrir esta sección')}};root.appendChild(button);if(item.items?.length)await addItems(item.items,depth+1)}};await addItems(outline)}catch{root.innerHTML='<span style="color:var(--muted);font-size:13px">No se pudo leer el índice.</span>'}}
function exportAnnotations(){if(!currentBook)return toast('Abre un PDF primero');const data={document:currentBook.name,exportedAt:new Date().toISOString(),annotations:annotations()};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`${currentBook.name.replace(/\.pdf$/i,'')}-anotaciones.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Anotaciones exportadas')}

function annotations(){return currentBook?getJSON(key(currentBook.id,'annotations'),[]):[]}
function setAnnotations(items){if(currentBook)setJSON(key(currentBook.id,'annotations'),items)}
function annotationStyle(color){return {yellow:'rgba(255,213,75,.48)',green:'rgba(122,205,142,.44)',pink:'rgba(244,131,177,.42)'}[color]||'rgba(255,213,75,.48)'}
function renderAnnotations(){const layer=$('annotationLayer');layer.innerHTML='';if(!currentBook)return;for(const mark of annotations().filter(a=>a.page===currentPage)){for(const rect of mark.rects){const el=document.createElement('i');el.className=`annotation ${mark.type}`;el.style.left=`${rect.x*100}%`;el.style.top=`${rect.y*100}%`;el.style.width=`${rect.w*100}%`;el.style.height=`${rect.h*100}%`;if(mark.type==='highlight')el.style.background=annotationStyle(mark.color);layer.appendChild(el)}}}
function selectedRects(){const sel=window.getSelection(),layer=$('textLayer');if(!sel?.rangeCount||sel.isCollapsed||!layer.contains(sel.anchorNode)||!layer.contains(sel.focusNode))return null;const pageBox=$('canvasWrap').getBoundingClientRect();const rects=[...sel.getRangeAt(0).getClientRects()].map(r=>({x:(r.left-pageBox.left)/pageBox.width,y:(r.top-pageBox.top)/pageBox.height,w:r.width/pageBox.width,h:r.height/pageBox.height})).filter(r=>r.w>0&&r.h>0&&r.x>=-.02&&r.y>=-.02);return rects.length?rects:null}
function hideAnnotationActions(){$('annotationActions').classList.remove('show')}
function showAnnotationActions(){const rects=selectedRects();if(!rects){hideAnnotationActions();return}const r=window.getSelection().getRangeAt(0).getBoundingClientRect(),actions=$('annotationActions'),width=240;actions.style.left=`${Math.min(window.innerWidth-width-8,Math.max(8,r.left+r.width/2-width/2))}px`;actions.style.top=`${r.top>62?r.top-45:r.bottom+8}px`;actions.classList.add('show')}
function saveAnnotation(type){const rects=selectedRects();if(!rects||!currentBook)return;const items=annotations();items.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,page:currentPage,type,color:annotationColor,rects,createdAt:Date.now()});setAnnotations(items);window.getSelection().removeAllRanges();hideAnnotationActions();renderAnnotations();toast(type==='highlight'?'Texto resaltado':'Texto subrayado')}
function clearPageAnnotations(){if(!currentBook)return;const existing=annotations(),count=existing.filter(a=>a.page===currentPage).length;if(!count)return toast('No hay anotaciones en esta página');if(!confirm(`¿Eliminar las ${count} anotaciones de esta página?`))return;setAnnotations(existing.filter(a=>a.page!==currentPage));renderAnnotations();$('toolPopover').classList.remove('open');toast('Anotaciones eliminadas')}

function openAiAssistant(){const text=window.getSelection()?.toString().trim();if(!text)return toast('Selecciona un fragmento para consultarlo');aiSelection=text.slice(0,7000);$('aiQuote').textContent=aiSelection;$('aiQuestion').value='Explícame este fragmento de forma clara y señala las ideas principales.';$('aiAnswer').textContent='';$('aiStatus').textContent='La primera vez descargará un modelo local (aprox. 900 MB) y requiere WebGPU.';$('aiPanel').hidden=false;hideAnnotationActions();$('aiQuestion').focus()}
function closeAiAssistant(){$('aiPanel').hidden=true}
async function getLocalAi(){if(localAiEngine)return localAiEngine;if(localAiLoading)return localAiLoading;if(!navigator.gpu)throw new Error('Este navegador no tiene WebGPU disponible. Prueba con una versión reciente de Chrome, Edge o Safari.');localAiLoading=(async()=>{const webllm=await import('https://esm.sh/@mlc-ai/web-llm@0.2.84');localAiEngine=await webllm.CreateMLCEngine('Llama-3.2-1B-Instruct-q4f16_1-MLC',{initProgressCallback:p=>{$('aiStatus').textContent=p.text||'Preparando IA local…'}});return localAiEngine})();try{return await localAiLoading}finally{localAiLoading=null}}
async function askLocalAi(){if(!aiSelection)return;const button=$('askAiSubmit'),question=$('aiQuestion').value.trim()||'Explica este texto.';button.disabled=true;$('aiAnswer').textContent='';try{$('aiStatus').textContent='Cargando la IA local…';const engine=await getLocalAi();$('aiStatus').textContent='Pensando en tu dispositivo…';const stream=await engine.chat.completions.create({messages:[{role:'system',content:'Eres un asistente de lectura riguroso. Responde siempre en español. Usa únicamente el fragmento proporcionado; si no basta para responder, dilo claramente.'},{role:'user',content:`Fragmento seleccionado:\n---\n${aiSelection}\n---\nPregunta: ${question}`}],temperature:.35,max_tokens:450,stream:true});for await(const chunk of stream){$('aiAnswer').textContent+=chunk.choices[0]?.delta?.content||''}$('aiStatus').textContent='Respuesta generada localmente. El fragmento no ha salido de tu navegador.'}catch(e){console.error(e);$('aiStatus').textContent=e.message||'No se pudo iniciar la IA local.';toast('La IA local no pudo iniciarse')}finally{button.disabled=false}}

async function search(query){if(!pdfDoc||!query.trim())return;const q=query.trim().toLowerCase();if(q===searchQuery&&searchMatches.length){searchIndex=(searchIndex+1)%searchMatches.length;await renderPage(searchMatches[searchIndex]);toast(`Coincidencia ${searchIndex+1} de ${searchMatches.length} · página ${currentPage}`);return}const token=++searchToken;searchQuery=q;searchMatches=[];searchIndex=-1;showLoader(true,'Buscando…',`“${query.trim()}”`);try{for(let i=1;i<=pdfDoc.numPages;i++){if(token!==searchToken)return;const p=await pdfDoc.getPage(i);const tc=await p.getTextContent();if(tc.items.some(x=>x.str.toLowerCase().includes(q)))searchMatches.push(i);$('loaderText').textContent=`Página ${i} de ${pdfDoc.numPages}`}if(!searchMatches.length){toast('No se encontró el texto');return}const afterCurrent=searchMatches.findIndex(p=>p>=currentPage);searchIndex=afterCurrent<0?0:afterCurrent;await renderPage(searchMatches[searchIndex]);toast(`Coincidencia ${searchIndex+1} de ${searchMatches.length} · página ${currentPage}`)}finally{showLoader(false)}}

function showEmpty(){$('emptyState').hidden=false;$('canvasWrap').hidden=true;$('docTitle').textContent='Paper Reader';$('docMeta').textContent='Tus documentos se quedan en este dispositivo';$('pageStatus').textContent='Sin documento';$('pageJump').hidden=true;$('progressBar').style.width='0';$('outlineList').innerHTML='';renderBookmarks()}

$('fileInput').onchange=e=>addFile(e.target.files?.[0]);$('prevBtn').onclick=()=>renderPage(currentPage-1);$('nextBtn').onclick=()=>renderPage(currentPage+1);$('zoomIn').onclick=()=>zoom(.15);$('zoomOut').onclick=()=>zoom(-.15);$('fitBtn').onclick=fitWidth;$('bookmarkBtn').onclick=toggleBookmark;$('searchBtn').onclick=()=>search($('searchInput').value);$('searchInput').onkeydown=e=>{if(e.key==='Enter')search(e.target.value)};$('themeSelect').onchange=e=>{document.documentElement.dataset.theme=e.target.value;localStorage.setItem('paper.theme',e.target.value)};$('openSidebar').onclick=()=>document.body.classList.add('sidebar-open');$('closeSidebar').onclick=()=>document.body.classList.remove('sidebar-open');
function toggleFocusMode(){const enabled=document.body.classList.toggle('focus-mode');$('focusBtn').textContent=enabled?'×':'⛶';$('focusBtn').title=enabled?'Salir del modo enfoque':'Modo enfoque';$('focusBtn').setAttribute('aria-label',$('focusBtn').title);if(enabled&&pdfDoc)fitWidth()}
$('focusBtn').onclick=toggleFocusMode;
$('pageJump').onchange=e=>{const page=Number(e.target.value);if(Number.isInteger(page)&&pdfDoc)renderPage(page);else if(pdfDoc)e.target.value=currentPage};$('exportNotes').onclick=exportAnnotations;
$('toolsBtn').onclick=()=>{const pop=$('toolPopover'),isOpen=pop.classList.toggle('open');$('toolsBtn').setAttribute('aria-expanded',String(isOpen))};
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{annotationColor=b.dataset.color;document.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('active',x===b));toast(`Color ${b.textContent.toLowerCase()} seleccionado`)});
document.querySelectorAll('[data-annotation]').forEach(b=>b.onclick=()=>saveAnnotation(b.dataset.annotation));$('clearPageNotes').onclick=clearPageAnnotations;
$('askAiBtn').onclick=openAiAssistant;$('closeAiPanel').onclick=closeAiAssistant;$('askAiSubmit').onclick=askLocalAi;$('aiPanel').onclick=e=>{if(e.target===$('aiPanel'))closeAiAssistant()};$('aiQuestion').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')askLocalAi()};
function setUiScale(value){const n=Math.max(.85,Math.min(1.25,value));document.documentElement.style.setProperty('--ui-scale',n);localStorage.setItem('paper.ui-scale',n)}
$('uiSmaller').onclick=()=>setUiScale(Number(localStorage.getItem('paper.ui-scale')||1)-.05);$('uiLarger').onclick=()=>setUiScale(Number(localStorage.getItem('paper.ui-scale')||1)+.05);
document.addEventListener('selectionchange',()=>requestAnimationFrame(showAnnotationActions));document.addEventListener('pointerdown',e=>{if(!e.target.closest('.annotation-actions')&&!e.target.closest('.textLayer'))hideAnnotationActions();if(!e.target.closest('.tool-menu'))$('toolPopover').classList.remove('open')});
window.addEventListener('keydown',e=>{if(e.target.matches?.('input,select,textarea'))return;if(e.key==='ArrowRight'||e.key==='PageDown')renderPage(currentPage+1);if(e.key==='ArrowLeft'||e.key==='PageUp')renderPage(currentPage-1);if(e.key==='+'||e.key==='=')zoom(.15);if(e.key==='-')zoom(-.15);if(e.key==='b'||e.key==='B')toggleBookmark();if(e.key==='f'||e.key==='F')toggleFocusMode();if(e.key==='Escape'){if(document.body.classList.contains('focus-mode'))toggleFocusMode();hideAnnotationActions();$('toolPopover').classList.remove('open')}});
let sx=null;document.addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true});document.addEventListener('touchend',e=>{if(sx==null||!pdfDoc)return;const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>110){dx<0?renderPage(currentPage+1):renderPage(currentPage-1)}sx=null},{passive:true});
let resizeTimer=null;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(pdfDoc&&(window.innerWidth<900||document.body.classList.contains('focus-mode')))fitWidth()},140)});

(async function init(){document.documentElement.dataset.theme=localStorage.getItem('paper.theme')||'dark';$('themeSelect').value=document.documentElement.dataset.theme;setUiScale(Number(localStorage.getItem('paper.ui-scale')||1));document.querySelector('[data-color="yellow"]').classList.add('active');await openDb();await renderLibrary();const books=(await dbAll()).sort((a,b)=>b.openedAt-a.openedAt);if(books[0])openStored(books[0].id);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})})();
