import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';

const $=id=>document.getElementById(id);
const DB_NAME='paper-reader-db', STORE='pdfs';
let db=null, pdfDoc=null, currentBook=null, currentPage=1, scale=1.25, renderTask=null, searchToken=0;

function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),1600)}
function showLoader(show,title='Abriendo PDF…',text='Preparando documento'){ $('loader').classList.toggle('show',show);$('loaderTitle').textContent=title;$('loaderText').textContent=text }
function key(id,suffix){return `paper.${id}.${suffix}`}
function getJSON(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function setJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
function bookId(file){return `${file.name}:${file.size}:${file.lastModified}`}

function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function dbPut(record){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function dbGet(id){return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function dbAll(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function dbDelete(id){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}

async function renderLibrary(){const books=(await dbAll()).sort((a,b)=>b.openedAt-a.openedAt);$('library').innerHTML=books.length?books.map(b=>`<button class="book ${currentBook?.id===b.id?'active':''}" data-id="${encodeURIComponent(b.id)}"><strong>${escapeHtml(b.name)}</strong><small>${b.pages?b.pages+' páginas · ':''}${new Date(b.openedAt).toLocaleDateString()}</small></button>`).join(''):'<span style="color:var(--muted);font-size:13px">Aún no hay PDFs guardados.</span>';document.querySelectorAll('.book').forEach(el=>{el.onclick=()=>openStored(decodeURIComponent(el.dataset.id));el.oncontextmenu=async e=>{e.preventDefault();if(confirm('¿Eliminar este PDF de la biblioteca local?')){await dbDelete(decodeURIComponent(el.dataset.id));if(currentBook?.id===decodeURIComponent(el.dataset.id)){pdfDoc=null;currentBook=null;showEmpty()}await renderLibrary()}}})}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}

async function addFile(file){if(!file)return;if(!(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')))return toast('Selecciona un PDF');showLoader(true,'Guardando PDF…','Se queda solo en este dispositivo');try{const id=bookId(file),buffer=await file.arrayBuffer();await dbPut({id,name:file.name,blob:new Blob([buffer],{type:'application/pdf'}),openedAt:Date.now(),pages:null});await openStored(id)}catch(e){console.error(e);toast('No se pudo guardar el PDF')}finally{showLoader(false)}}
async function openStored(id){showLoader(true);try{const rec=await dbGet(id);if(!rec)throw new Error('Documento no encontrado');const bytes=new Uint8Array(await rec.blob.arrayBuffer());pdfDoc=await pdfjsLib.getDocument({data:bytes}).promise;rec.pages=pdfDoc.numPages;rec.openedAt=Date.now();await dbPut(rec);currentBook=rec;currentPage=Math.min(Number(localStorage.getItem(key(id,'page'))||1),pdfDoc.numPages);scale=Number(localStorage.getItem(key(id,'scale'))||1.25);$('emptyState').hidden=true;$('canvasWrap').hidden=false;$('docTitle').textContent=rec.name;$('docMeta').textContent=`${pdfDoc.numPages} páginas · guardado localmente`;await renderPage(currentPage);renderBookmarks();renderLibrary();document.body.classList.remove('sidebar-open')}catch(e){console.error(e);toast('No se pudo abrir el PDF')}finally{showLoader(false)}}

async function renderPage(num){if(!pdfDoc)return;if(renderTask){try{renderTask.cancel()}catch{}}currentPage=Math.max(1,Math.min(pdfDoc.numPages,num));const page=await pdfDoc.getPage(currentPage);const viewport=page.getViewport({scale});const dpr=Math.min(window.devicePixelRatio||1,2);const canvas=$('pdfCanvas'),ctx=canvas.getContext('2d');canvas.width=Math.floor(viewport.width*dpr);canvas.height=Math.floor(viewport.height*dpr);canvas.style.width=`${viewport.width}px`;canvas.style.height=`${viewport.height}px`;$('canvasWrap').style.width=`${viewport.width}px`;$('canvasWrap').style.height=`${viewport.height}px`;renderTask=page.render({canvasContext:ctx,viewport,transform:[dpr,0,0,dpr,0,0]});await renderTask.promise.catch(()=>{});localStorage.setItem(key(currentBook.id,'page'),String(currentPage));localStorage.setItem(key(currentBook.id,'scale'),String(scale));$('pageStatus').textContent=`Página ${currentPage} de ${pdfDoc.numPages}`;$('progressBar').style.width=`${(currentPage/pdfDoc.numPages)*100}%`;$('prevBtn').disabled=currentPage===1;$('nextBtn').disabled=currentPage===pdfDoc.numPages;$('viewer').scrollTo({top:0,left:0});renderTextLayer(page,viewport)}
async function renderTextLayer(page,viewport){const layer=$('textLayer');layer.innerHTML='';layer.style.width=`${viewport.width}px`;layer.style.height=`${viewport.height}px`;try{const tc=await page.getTextContent();for(const item of tc.items){if(!item.str)continue;const tx=pdfjsLib.Util.transform(viewport.transform,item.transform);const span=document.createElement('span');span.textContent=item.str;span.style.left=`${tx[4]}px`;span.style.top=`${tx[5]}px`;span.style.fontSize=`${Math.hypot(tx[2],tx[3])}px`;layer.appendChild(span)}}catch{}}

async function fitWidth(){if(!pdfDoc)return;const p=await pdfDoc.getPage(currentPage);const base=p.getViewport({scale:1});const available=$('viewer').clientWidth-24;scale=Math.max(.35,Math.min(3,available/base.width));renderPage(currentPage)}
function zoom(delta){scale=Math.max(.4,Math.min(3.5,scale+delta));renderPage(currentPage)}
function renderBookmarks(){if(!currentBook){$('bookmarkList').innerHTML='';return}const list=getJSON(key(currentBook.id,'bookmarks'),[]);$('bookmarkList').innerHTML=list.length?list.sort((a,b)=>a-b).map(p=>`<button class="bookmark" data-p="${p}"><strong>Página ${p}</strong><small>Ir al marcador</small></button>`).join(''):'<span style="color:var(--muted);font-size:13px">Sin marcadores.</span>';document.querySelectorAll('.bookmark').forEach(b=>b.onclick=()=>renderPage(Number(b.dataset.p)))}
function toggleBookmark(){if(!currentBook)return;let list=getJSON(key(currentBook.id,'bookmarks'),[]);if(list.includes(currentPage)){list=list.filter(p=>p!==currentPage);toast('Marcador eliminado')}else{list.push(currentPage);toast('Página marcada')}setJSON(key(currentBook.id,'bookmarks'),list);renderBookmarks()}

async function search(query){if(!pdfDoc||!query.trim())return;const token=++searchToken;showLoader(true,'Buscando…',`“${query}”`);try{const q=query.toLowerCase();for(let i=currentPage;i<=pdfDoc.numPages;i++){if(token!==searchToken)return;const p=await pdfDoc.getPage(i);const tc=await p.getTextContent();const text=tc.items.map(x=>x.str).join(' ').toLowerCase();$('loaderText').textContent=`Página ${i} de ${pdfDoc.numPages}`;if(text.includes(q)){await renderPage(i);toast(`Encontrado en la página ${i}`);return}}for(let i=1;i<currentPage;i++){if(token!==searchToken)return;const p=await pdfDoc.getPage(i);const tc=await p.getTextContent();const text=tc.items.map(x=>x.str).join(' ').toLowerCase();if(text.includes(q)){await renderPage(i);toast(`Encontrado en la página ${i}`);return}}toast('No se encontró el texto')}finally{showLoader(false)}}

function showEmpty(){$('emptyState').hidden=false;$('canvasWrap').hidden=true;$('docTitle').textContent='Paper Reader';$('docMeta').textContent='Tus documentos se quedan en este dispositivo';$('pageStatus').textContent='Sin documento';$('progressBar').style.width='0';renderBookmarks()}

$('fileInput').onchange=e=>addFile(e.target.files?.[0]);$('prevBtn').onclick=()=>renderPage(currentPage-1);$('nextBtn').onclick=()=>renderPage(currentPage+1);$('zoomIn').onclick=()=>zoom(.15);$('zoomOut').onclick=()=>zoom(-.15);$('fitBtn').onclick=fitWidth;$('bookmarkBtn').onclick=toggleBookmark;$('searchBtn').onclick=()=>search($('searchInput').value);$('searchInput').onkeydown=e=>{if(e.key==='Enter')search(e.target.value)};$('themeSelect').onchange=e=>{document.documentElement.dataset.theme=e.target.value;localStorage.setItem('paper.theme',e.target.value)};$('openSidebar').onclick=()=>document.body.classList.add('sidebar-open');$('closeSidebar').onclick=()=>document.body.classList.remove('sidebar-open');
window.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='PageDown')renderPage(currentPage+1);if(e.key==='ArrowLeft'||e.key==='PageUp')renderPage(currentPage-1)});
let sx=null;document.addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true});document.addEventListener('touchend',e=>{if(sx==null||!pdfDoc)return;const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>110){dx<0?renderPage(currentPage+1):renderPage(currentPage-1)}sx=null},{passive:true});
window.addEventListener('resize',()=>{if(pdfDoc&&window.innerWidth<900)fitWidth()});

(async function init(){document.documentElement.dataset.theme=localStorage.getItem('paper.theme')||'dark';$('themeSelect').value=document.documentElement.dataset.theme;await openDb();await renderLibrary();const books=(await dbAll()).sort((a,b)=>b.openedAt-a.openedAt);if(books[0])openStored(books[0].id);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})})();
